---
title: "YoutubeTrendsAnalysis"
author: "Kozlov Valentin"
date: '17 января 2018 г '
output: html_document
---

```{r setup, include=FALSE}
chooseCRANmirror(graphics=FALSE, ind=1)
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
install.packages("ggplot2")
install.packages("sqldf")
library(ggplot2)
require(sqldf)
```

```{r}
library(jsonlite)
cat_names <- fromJSON("dataset/GB_category_id.json")
names <- cat_names$items$snippet$title
head(names)
map <- table(cat_names$items$id,  cat_names$items$snippet$title)
summary(map)

```

```{r}
smoke <- matrix(cat_names$items$snippet$title, ncol=1, byrow=TRUE)
rownames(smoke) <- c(cat_names$items$id)
colnames(smoke) <- c("Categories")
smoke <- as.table(smoke)
smoke


```

```{r}
GBdataset <- read.csv("dataset/GBvideos.csv", 
                      header = TRUE, 
                      sep = ",", 
                      quote = "\"", 
                      dec = ".", 
                      fill = TRUE, 
                      comment.char = "")
View(GBdataset)
USAdataset <- read.csv("dataset/USvideos.csv", 
                      header = TRUE, 
                      sep = ",", 
                      quote = "\"", 
                      dec = ".", 
                      fill = TRUE, 
                      comment.char = "")
View(USAdataset)
```

```{r}
GBdataset_size <- nrow(GBdataset)
USAdataset_size <- nrow(USAdataset)
```

```{r}
GBdublicates <- duplicated(GBdataset)
length(GBdublicates)
if (length(GBdataset$video_id[GBdublicates]) == 0) {
  print("Dublicates were not found in GBdataset")
} else {
  print("GBdataset contains dublicates")
}

USAdublicates <- duplicated(USAdataset)
length(USAdublicates)
if (length(USAdataset$video_id[USAdublicates]) == 0) {
  print("Dublicates were not found in USAdataset")
} else {
  print("USAdataset contains dublicates")
}
```

```{r}
GBdataset <- sqldf("select * from GBdataset where views != 0")
Number_videos_with_0_views_GB <- GBdataset_size - nrow(GBdataset)
GBdataset_size <- nrow(GBdataset)

USAdataset <- sqldf("select * from USAdataset where views != 0")
Number_videos_with_0_views_USA <- USAdataset_size - nrow(USAdataset)
USAdataset_size <- nrow(USAdataset)

summary(GBdataset$views)

str(GBdataset)
```

```{r}
ggplot(GBdataset, aes(x = views)) + geom_dotplot()
ggplot(GBdataset, aes(x = as.numeric(as.character(category_id)))) + geom_histogram()
```

```{r}
plot(GBdataset$views)


views <- GBdataset$views

hist(views, xlim=range(tmp), breaks = 100, xlab = "Views")

hist(views, xlim=c(0,10000000), breaks = 300, xlab = "Views")

hist(views, xlim=c(1000000,15000000), breaks = 100, xlab = "Views")
```


```{r}
likes <- GBdataset$likes

hist(likes, xlim=range(likes), breaks = 100, xlab = "Likes")

hist(likes, xlim=range(0,100000), breaks = 1000, xlab = "Likes")
```

```{r}
categories <- as.numeric(as.character(GBdataset$category_id))

hist(categories, breaks = 30, xlab = "Categories")
```