SentimentAnalysis

```{r}

library(syuzhet) 
GBcomments <- read.csv("dataset/GBcomments.csv", 
                      header = TRUE, 
                      sep = ",", 
                      quote = "\"", 
                      dec = ".", 
                      fill = TRUE, 
                      comment.char = "")

#sentiment analysis core
commentsText <- GBcomments$comment_text
commentsSet <- as.character(commentsText)
syuzhet_vector <- get_sentiment(commentsSet, method="afinn")


#add negative/positive rows

for (i in 1:nrow(GBcomments)) {
  
  if (syuzhet_vector[i] > 0) {
    GBcomments$is_positive[i] <- 1 #+ as.integer(GBcomments$likes[i])
    GBcomments$is_negative[i] <- 0
  } else if (syuzhet_vector[i] == 0) {
    GBcomments$is_positive[i] <- 0
    GBcomments$is_negative[i] <- 0
  }
    else if (syuzhet_vector[i] < 0) {
    GBcomments$is_positive[i] <- 0
    GBcomments$is_negative[i] <- 1 #+ as.integer(GBcomments$likes[i])
    }
  
}

View(GBcomments)

```

```{r}

UScomments <- read.csv("dataset/UScomments.csv", 
                      header = TRUE, 
                      sep = ",", 
                      quote = "\"", 
                      dec = ".", 
                      fill = TRUE, 
                      comment.char = "")

#sentiment analysis core
UScommentsText <- UScomments$comment_text
UScommentsSet <- as.character(UScommentsText)
USsyuzhet_vector <- get_sentiment(UScommentsSet, method="afinn")


#add negative/positive rows

for (i in 1:nrow(UScomments)) {
  
  if (USsyuzhet_vector[i] > 0) {
    UScomments$is_positive[i] <- 1 
    UScomments$is_negative[i] <- 0
  } else if (USsyuzhet_vector[i] == 0) {
    UScomments$is_positive[i] <- 0
    UScomments$is_negative[i] <- 0
  }
    else if (USsyuzhet_vector[i] < 0) {
    UScomments$is_positive[i] <- 0
    UScomments$is_negative[i] <- 1
    }
  
}

View(UScomments)
```
